# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('client', models.CharField(choices=[('A', 'Client A'), ('B', 'Client B'), ('C', 'Client C')], max_length=9)),
                ('priority', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=3)),
                ('target_date', models.DateTimeField()),
                ('department', models.CharField(choices=[('POLICIES', 'Policies'), ('BILLING', 'Billing'), ('CLAIMS', 'Claims'), ('REPORTS', 'Reports')], max_length=12)),
            ],
        ),
    ]
