# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feautures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=3),
        ),
    ]
