# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feautures', '0003_auto_20180718_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='target_date',
            field=models.DateTimeField(verbose_name='%m/%d/%y'),
        ),
    ]
